version: '3.8'

services:
  admin:
    image: ${DOCKER_REGISTRY-}admin
    build:
      context: .
      dockerfile: src/Presentation/Admin/Dockerfile
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Presentation/Api/Dockerfile